from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pytest

from option_pricing.models.heston import HestonParams
from option_pricing.numerics.quadrature import QuadratureConfig
from option_pricing.pricers.heston import (
    heston_price_call_from_ctx,
    heston_price_put_from_ctx,
)
from option_pricing.types import MarketData


@dataclass(frozen=True, slots=True)
class HestonReferenceCase:
    """Frozen Heston vanilla price regression case.

    The reference prices below were generated from an independent P1/P2 Heston
    quadrature implementation using SciPy quad with tight tolerances. They are
    intentionally not generated by this repo's production pricer.

    REVIEW: Before treating these as permanent benchmark values, verify the
    pricing convention in docs/notes/heston_pricing_conventions.md and re-bless
    the numbers from one trusted external source or notebook.
    """

    name: str
    params: HestonParams
    tau: float
    strikes: np.ndarray
    expected_calls: np.ndarray
    expected_puts: np.ndarray
    atol: float = 2.5e-5
    rtol: float = 2.5e-7


MARKET = MarketData(spot=100.0, rate=0.02, dividend_yield=0.005)
CTX = MARKET.to_context()

# Use a denser fixed-rule configuration than the default so this test is a
# reference-price regression, not a test of the default speed/accuracy trade-off.
ROBUST_QUAD_CFG = QuadratureConfig(u_max=260.0, n_panels=56, nodes_per_panel=32)
BACKEND_AGREEMENT_QUAD_CFG = QuadratureConfig(
    u_max=220.0, n_panels=44, nodes_per_panel=24
)

REFERENCE_CASES = (
    HestonReferenceCase(
        name="mild_negative_skew",
        params=HestonParams(kappa=2.0, vbar=0.04, eta=0.55, rho=-0.70, v=0.05),
        tau=1.0,
        strikes=np.array([80.0, 100.0, 120.0]),
        expected_calls=np.array([22.9512476868, 8.2951033767, 1.1469698196]),
        expected_puts=np.array([1.8658936321, 6.8137227881, 19.2695626972]),
    ),
    HestonReferenceCase(
        name="high_vol_of_vol",
        params=HestonParams(kappa=1.5, vbar=0.04, eta=1.10, rho=-0.65, v=0.04),
        tau=0.5,
        strikes=np.array([80.0, 100.0, 120.0]),
        expected_calls=np.array([21.4671092349, 4.6073913832, 0.1936950957]),
        expected_puts=np.array([0.9207836951, 3.8620625183, 19.2493629059]),
        atol=5.0e-5,
    ),
    HestonReferenceCase(
        name="short_maturity",
        params=HestonParams(kappa=2.0, vbar=0.04, eta=0.70, rho=-0.50, v=0.05),
        tau=0.08,
        strikes=np.array([90.0, 100.0, 110.0]),
        expected_calls=np.array([10.3262166253, 2.4870302206, 0.0991901545]),
        expected_puts=np.array([0.2223237650, 2.3671501534, 9.9633228805]),
        atol=7.5e-5,
    ),
    HestonReferenceCase(
        name="long_maturity",
        params=HestonParams(kappa=1.2, vbar=0.035, eta=0.45, rho=-0.40, v=0.06),
        tau=3.0,
        strikes=np.array([70.0, 100.0, 130.0]),
        expected_calls=np.array([34.9751634936, 14.7265713044, 4.4531432758]),
        expected_puts=np.array([2.3874868842, 10.3918307026, 28.3713386815]),
    ),
    HestonReferenceCase(
        name="positive_rho",
        params=HestonParams(kappa=1.8, vbar=0.04, eta=0.60, rho=0.45, v=0.04),
        tau=1.25,
        strikes=np.array([80.0, 100.0, 120.0]),
        expected_calls=np.array([22.1829028202, 8.9092874540, 3.7980984689]),
        expected_puts=np.array([0.8307467201, 7.0633295945, 21.4583388500]),
    ),
)


def _format_price_table(
    *,
    strikes: np.ndarray,
    actual: np.ndarray,
    expected: np.ndarray,
    label: str,
) -> str:
    rows = [f"{label} price regression mismatch", "strike | actual | expected | diff"]
    for strike, actual_px, expected_px in zip(strikes, actual, expected, strict=True):
        rows.append(
            f"{float(strike):8.3f} | {float(actual_px): .12f} | "
            f"{float(expected_px): .12f} | {float(actual_px - expected_px): .12e}"
        )
    return "\n".join(rows)


def _price_calls(
    case: HestonReferenceCase, *, backend: str = "gauss_legendre"
) -> np.ndarray:
    return np.asarray(
        heston_price_call_from_ctx(
            strike=case.strikes,
            ctx=CTX,
            tau=case.tau,
            params=case.params,
            backend=backend,
            quad_cfg=ROBUST_QUAD_CFG if backend == "gauss_legendre" else None,
        ),
        dtype=np.float64,
    )


def _price_puts(
    case: HestonReferenceCase, *, backend: str = "gauss_legendre"
) -> np.ndarray:
    return np.asarray(
        heston_price_put_from_ctx(
            strike=case.strikes,
            ctx=CTX,
            tau=case.tau,
            params=case.params,
            backend=backend,
            quad_cfg=ROBUST_QUAD_CFG if backend == "gauss_legendre" else None,
        ),
        dtype=np.float64,
    )


@pytest.mark.parametrize("case", REFERENCE_CASES, ids=lambda case: case.name)
def test_heston_reference_call_prices(case: HestonReferenceCase) -> None:
    actual = _price_calls(case)

    assert np.allclose(
        actual,
        case.expected_calls,
        atol=case.atol,
        rtol=case.rtol,
    ), _format_price_table(
        strikes=case.strikes,
        actual=actual,
        expected=case.expected_calls,
        label=f"{case.name} call",
    )


@pytest.mark.parametrize("case", REFERENCE_CASES, ids=lambda case: case.name)
def test_heston_reference_put_prices(case: HestonReferenceCase) -> None:
    actual = _price_puts(case)

    assert np.allclose(
        actual,
        case.expected_puts,
        atol=case.atol,
        rtol=case.rtol,
    ), _format_price_table(
        strikes=case.strikes,
        actual=actual,
        expected=case.expected_puts,
        label=f"{case.name} put",
    )


@pytest.mark.parametrize("case", REFERENCE_CASES, ids=lambda case: case.name)
def test_heston_reference_prices_obey_static_no_arbitrage(
    case: HestonReferenceCase,
) -> None:
    calls = _price_calls(case)
    puts = _price_puts(case)
    df = CTX.df(case.tau)
    forward = CTX.fwd(case.tau)

    parity_error = (calls - puts) - df * (forward - case.strikes)

    assert np.all(np.isfinite(calls))
    assert np.all(np.isfinite(puts))
    assert np.all(calls >= -1.0e-10)
    assert np.all(puts >= -1.0e-10)
    assert np.all(np.diff(calls) <= 1.0e-8)
    assert np.all(np.diff(puts) >= -1.0e-8)
    assert float(np.max(np.abs(parity_error))) < 2.0e-8


@pytest.mark.slow
@pytest.mark.parametrize("case", REFERENCE_CASES, ids=lambda case: case.name)
def test_heston_reference_prices_quad_backend_agrees_with_fixed_rule(
    case: HestonReferenceCase,
) -> None:
    """Cross-check the production fixed-rule backend against SciPy quad.

    This is intentionally marked slow because the quad backend performs scalar
    integration per strike/probability pair.
    """
    gl_calls = np.asarray(
        heston_price_call_from_ctx(
            strike=case.strikes,
            ctx=CTX,
            tau=case.tau,
            params=case.params,
            backend="gauss_legendre",
            quad_cfg=BACKEND_AGREEMENT_QUAD_CFG,
        ),
        dtype=np.float64,
    )
    quad_calls = _price_calls(case, backend="quad")

    assert np.allclose(
        gl_calls, quad_calls, atol=1.5e-4, rtol=1.0e-5
    ), _format_price_table(
        strikes=case.strikes,
        actual=gl_calls,
        expected=quad_calls,
        label=f"{case.name} gauss_legendre vs quad call",
    )
