from __future__ import annotations

# ruff: noqa: E402
import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from option_pricing.marketdata.config import (  # noqa: E402
    AlpacaConfig,
    FredConfig,
    PipelineConfig,
    StorageConfig,
)
from option_pricing.marketdata.errors import MarketDataProviderError  # noqa: E402
from option_pricing.marketdata.pipeline import MarketDataPipeline  # noqa: E402

DEFAULT_DATA_ROOT = Path("data")
DEFAULT_RATE_SERIES = "DGS3MO"
DEFAULT_TIMEFRAME = "1Day"


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Fetch provider-backed marketdata snapshots and backfills through "
            "MarketDataPipeline."
        )
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    snapshot = subparsers.add_parser(
        "snapshot",
        help="Fetch, clean, and persist one provider-backed market snapshot.",
    )
    _add_common_run_options(snapshot)
    _add_common_provider_options(snapshot)
    snapshot.add_argument("--underlying", required=True, help="Underlying symbol.")
    snapshot.add_argument(
        "--asof",
        default=None,
        help="Optional valuation timestamp accepted by MarketDataPipeline.snapshot.",
    )
    snapshot.add_argument(
        "--rate-series",
        default=DEFAULT_RATE_SERIES,
        help="FRED rate series ID used for the risk-free rate.",
    )
    snapshot.add_argument("--expiry-gte", default=None)
    snapshot.add_argument("--expiry-lte", default=None)
    snapshot.add_argument("--strike-gte", type=float, default=None)
    snapshot.add_argument("--strike-lte", type=float, default=None)
    snapshot.add_argument("--option-type", default=None)

    backfill_fred = subparsers.add_parser(
        "backfill-fred",
        help="Backfill one or more FRED series into Bronze and Silver storage.",
    )
    _add_common_run_options(backfill_fred)
    backfill_fred.add_argument(
        "--series",
        nargs="+",
        required=True,
        help="One or more FRED series IDs.",
    )
    backfill_fred.add_argument("--start", required=True, help="Start date.")
    backfill_fred.add_argument("--end", default=None, help="Optional end date.")

    backfill_bars = subparsers.add_parser(
        "backfill-bars",
        help="Backfill Alpaca equity bars into Bronze and Silver storage.",
    )
    _add_common_run_options(backfill_bars)
    _add_common_provider_options(backfill_bars)
    backfill_bars.add_argument(
        "--symbols",
        nargs="+",
        required=True,
        help="One or more equity symbols.",
    )
    backfill_bars.add_argument("--start", required=True, help="Start timestamp/date.")
    backfill_bars.add_argument("--end", required=True, help="End timestamp/date.")
    backfill_bars.add_argument(
        "--timeframe",
        default=DEFAULT_TIMEFRAME,
        help="Alpaca bar timeframe.",
    )

    return parser.parse_args(argv)


def _add_common_run_options(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--run-id",
        default=None,
        help="Optional run ID; generated by the pipeline when omitted.",
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=DEFAULT_DATA_ROOT,
        help="Local data root for Bronze, Silver, Gold, and metadata artifacts.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace existing artifacts for the requested partitions.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit one stable JSON object instead of human-readable text.",
    )


def _add_common_provider_options(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--feed",
        default=None,
        help="Optional Alpaca feed override for this command.",
    )


def _build_config(args: argparse.Namespace) -> PipelineConfig:
    default_alpaca = AlpacaConfig()
    feed = getattr(args, "feed", None) or default_alpaca.feed
    return PipelineConfig(
        alpaca=AlpacaConfig(feed=feed),
        fred=FredConfig(),
        storage=StorageConfig(root=args.data_root),
    )


def _build_pipeline(args: argparse.Namespace) -> MarketDataPipeline:
    return MarketDataPipeline(_build_config(args))


def _run_command(args: argparse.Namespace) -> tuple[str, object]:
    pipeline = _build_pipeline(args)
    if args.command == "snapshot":
        return (
            "snapshot",
            pipeline.snapshot(
                args.underlying,
                asof=args.asof,
                run_id=args.run_id,
                rate_series_id=args.rate_series,
                expiry_gte=args.expiry_gte,
                expiry_lte=args.expiry_lte,
                strike_gte=args.strike_gte,
                strike_lte=args.strike_lte,
                option_type=args.option_type,
                feed=args.feed,
                overwrite=args.overwrite,
            ),
        )
    if args.command == "backfill-fred":
        return (
            "backfill-fred",
            pipeline.backfill_fred(
                args.series,
                start=args.start,
                end=args.end,
                run_id=args.run_id,
                overwrite=args.overwrite,
            ),
        )
    if args.command == "backfill-bars":
        return (
            "backfill-bars",
            pipeline.backfill_bars(
                args.symbols,
                start=args.start,
                end=args.end,
                timeframe=args.timeframe,
                feed=args.feed,
                run_id=args.run_id,
                overwrite=args.overwrite,
            ),
        )

    raise ValueError(f"Unsupported command: {args.command}")


def _emit_result(command: str, result: object, *, as_json: bool) -> None:
    if as_json:
        print(json.dumps(_result_payload(command, result), indent=2, sort_keys=True))
        return

    if command == "snapshot":
        lines = _snapshot_summary_lines(result)
    elif command == "backfill-fred":
        lines = _backfill_summary_lines(result, dataset="fred_series")
    elif command == "backfill-bars":
        lines = _backfill_summary_lines(result, dataset="equity_bars")
    else:
        raise ValueError(f"Unsupported command: {command}")
    print("\n".join(lines))


def _result_payload(command: str, result: object) -> dict[str, object]:
    if command == "snapshot":
        return _snapshot_payload(result)
    if command == "backfill-fred":
        return _backfill_payload(result, command=command, dataset="fred_series")
    if command == "backfill-bars":
        return _backfill_payload(result, command=command, dataset="equity_bars")
    raise ValueError(f"Unsupported command: {command}")


def _snapshot_payload(result: object) -> dict[str, object]:
    main_paths = _snapshot_main_artifact_paths(result)
    return {
        "command": "snapshot",
        "underlying": _jsonable(getattr(result, "underlying", None)),
        "asof": _jsonable(getattr(result, "asof", None)),
        "run_id": _jsonable(getattr(result, "run_id", None)),
        "spot": _jsonable(getattr(result, "spot", None)),
        "rate": _jsonable(getattr(result, "rate", None)),
        "rate_source": _jsonable(getattr(result, "rate_source", None)),
        "rate_observation_date": _jsonable(
            getattr(result, "rate_observation_date", None)
        ),
        "dividend_yield": _jsonable(getattr(result, "dividend_yield", None)),
        "accepted_quote_count": _jsonable(
            getattr(result, "accepted_quote_count", None)
        ),
        "rejected_quote_count": _jsonable(
            getattr(result, "rejected_quote_count", None)
        ),
        "main_artifact_paths": {
            name: str(path) for name, path in main_paths.items() if path is not None
        },
        "artifact_paths": [str(path) for path in _artifact_paths(result)],
        "warnings": list(_warnings_from_result(result)),
    }


def _backfill_payload(
    result: object,
    *,
    command: str,
    dataset: str,
) -> dict[str, object]:
    metadata = getattr(result, "metadata", None)
    stats = getattr(result, "stats", None)
    return {
        "command": command,
        "run_id": _jsonable(getattr(metadata, "run_id", None)),
        "run_ids": [_jsonable(run_id) for run_id in getattr(result, "run_ids", ())],
        "dataset": dataset,
        "row_counts": {
            "rows_in": _jsonable(getattr(stats, "rows_in", 0)),
            "rows_out": _jsonable(getattr(stats, "rows_out", 0)),
        },
        "artifact_paths": [str(path) for path in _artifact_paths(result)],
        "warnings": list(_warnings_from_result(result)),
    }


def _snapshot_summary_lines(result: object) -> list[str]:
    lines = [
        "Market snapshot completed.",
        f"underlying: {getattr(result, 'underlying', None)}",
        f"asof: {_text(getattr(result, 'asof', None))}",
        f"run_id: {getattr(result, 'run_id', None)}",
        f"spot: {getattr(result, 'spot', None)}",
        f"rate: {getattr(result, 'rate', None)}",
        f"rate_source: {getattr(result, 'rate_source', None)}",
        f"dividend_yield: {getattr(result, 'dividend_yield', None)}",
        f"accepted_quote_count: {getattr(result, 'accepted_quote_count', None)}",
        f"rejected_quote_count: {getattr(result, 'rejected_quote_count', None)}",
        "main_artifact_paths:",
    ]
    main_paths = _snapshot_main_artifact_paths(result)
    lines.extend(
        f"  {name}: {path}" for name, path in main_paths.items() if path is not None
    )
    lines.extend(_warning_lines(_warnings_from_result(result)))
    return lines


def _backfill_summary_lines(result: object, *, dataset: str) -> list[str]:
    metadata = getattr(result, "metadata", None)
    stats = getattr(result, "stats", None)
    lines = [
        f"{dataset} backfill completed.",
        f"run_id: {getattr(metadata, 'run_id', None)}",
        f"dataset: {dataset}",
        f"rows_in: {getattr(stats, 'rows_in', 0)}",
        f"rows_out: {getattr(stats, 'rows_out', 0)}",
        "artifact_paths:",
    ]
    lines.extend(f"  - {path}" for path in _artifact_paths(result))
    lines.extend(_warning_lines(_warnings_from_result(result)))
    return lines


def _warning_lines(warnings: Sequence[str]) -> list[str]:
    if not warnings:
        return ["warnings: none"]
    return ["warnings:", *(f"  - {warning}" for warning in warnings)]


def _warnings_from_result(result: object) -> tuple[str, ...]:
    warnings = getattr(result, "warnings", None)
    if warnings is None:
        stats = getattr(result, "stats", None)
        warnings = getattr(stats, "warnings", ())
    if isinstance(warnings, str):
        return (warnings,)
    return tuple(str(warning) for warning in warnings)


def _artifact_paths(result: object) -> tuple[Path, ...]:
    paths = getattr(result, "artifact_paths", ())
    return tuple(Path(path) for path in paths)


def _snapshot_main_artifact_paths(result: object) -> dict[str, Path | None]:
    bronze_paths = getattr(result, "bronze_paths", None)
    silver_paths = getattr(result, "silver_paths", None)
    gold_paths = getattr(result, "gold_paths", None)
    bundle = getattr(result, "model_validation_bundle", None)
    return {
        "bronze_manifest": _optional_path(getattr(bronze_paths, "manifest", None)),
        "silver_manifest": _optional_path(getattr(silver_paths, "manifest", None)),
        "market_data": _optional_path(getattr(gold_paths, "market_data", None)),
        "market_manifest": _optional_path(getattr(gold_paths, "market_manifest", None)),
        "bundle_manifest": _optional_path(getattr(bundle, "manifest_path", None)),
    }


def _optional_path(value: object) -> Path | None:
    if value is None:
        return None
    return Path(value)


def _jsonable(value: object) -> object:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, datetime | date):
        return value.isoformat()
    isoformat = getattr(value, "isoformat", None)
    if callable(isoformat) and not isinstance(value, str):
        return isoformat()
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, Sequence) and not isinstance(
        value,
        (str, bytes, bytearray),
    ):
        return [_jsonable(item) for item in value]
    return value


def _text(value: object) -> str:
    jsonable = _jsonable(value)
    return "" if jsonable is None else str(jsonable)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        command, result = _run_command(args)
    except (
        MarketDataProviderError,
        ValueError,
        FileExistsError,
    ) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    _emit_result(command, result, as_json=args.json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
