"""Render D2 diagrams used by the docs.

We keep D2 sources under:

  docs/assets/diagrams/src/*.d2

and render SVG outputs to:

  docs/assets/diagrams/*.light.svg
  docs/assets/diagrams/*.dark.svg

Why two files?
Material for MkDocs toggles themes via `data-md-color-scheme` ("default" vs "slate").
SVGs generated by D2 can optionally react to *OS* theme via media queries, but that
doesn't track the MkDocs palette toggle. Rendering two explicit variants avoids
surprises when switching the site theme.

Usage:
  python scripts/render_d2_diagrams.py
  python scripts/render_d2_diagrams.py --check

Environment overrides:
  D2_LAYOUT=elk
  D2_THEME_LIGHT=5
  D2_THEME_DARK=200
  D2_PAD=0

Install D2:
  - curl -fsSL https://d2lang.com/install.sh | sh -s --
  - go install oss.terrastruct.com/d2@latest
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "docs" / "assets" / "diagrams" / "src"
OUT_DIR = ROOT / "docs" / "assets" / "diagrams"


@dataclass(frozen=True, slots=True)
class D2RenderConfig:
    layout: str
    theme_light: str
    theme_dark: str
    pad: str
    center: bool = True
    no_xml_tag: bool = True


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _d2_binary() -> str:
    d2 = shutil.which("d2")
    if d2:
        return d2

    raise FileNotFoundError(
        "Could not find the `d2` executable on PATH.\n\n"
        "Install D2 and re-run:\n"
        "  1) curl -fsSL https://d2lang.com/install.sh | sh -s --\n"
        "  2) go install oss.terrastruct.com/d2@latest\n"
    )


def _render_one(src: Path, out: Path, *, theme: str, cfg: D2RenderConfig) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)

    cmd: list[str] = [
        _d2_binary(),
        f"--layout={cfg.layout}",
        f"--theme={theme}",
        f"--pad={cfg.pad}",
    ]

    if cfg.center:
        cmd.append("--center")
    if cfg.no_xml_tag:
        cmd.append("--no-xml-tag")

    cmd.extend([str(src), str(out)])
    subprocess.run(cmd, check=True)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write outputs. Fail if rendered SVGs would change.",
    )
    args = parser.parse_args(argv)

    if not SRC_DIR.exists():
        print(f"No D2 source directory found: {SRC_DIR}")
        return

    d2_files = sorted(SRC_DIR.glob("*.d2"))
    if not d2_files:
        print(f"No .d2 files found under {SRC_DIR}")
        return

    cfg = D2RenderConfig(
        layout=os.environ.get("D2_LAYOUT", "elk"),
        theme_light=os.environ.get("D2_THEME_LIGHT", "5"),
        theme_dark=os.environ.get("D2_THEME_DARK", "200"),
        pad=os.environ.get("D2_PAD", "0"),
        center=os.environ.get("D2_CENTER", "1") not in {"0", "false", "False"},
        no_xml_tag=os.environ.get("D2_NO_XML_TAG", "1") not in {"0", "false", "False"},
    )

    if args.check:
        tmp = ROOT / ".tmp_d2_render"
        if tmp.exists():
            shutil.rmtree(tmp)
        tmp.mkdir(parents=True, exist_ok=True)

        changed: list[str] = []
        for src in d2_files:
            out_light = tmp / f"{src.stem}.light.svg"
            out_dark = tmp / f"{src.stem}.dark.svg"

            _render_one(src, out_light, theme=cfg.theme_light, cfg=cfg)
            _render_one(src, out_dark, theme=cfg.theme_dark, cfg=cfg)

            cur_light = OUT_DIR / f"{src.stem}.light.svg"
            cur_dark = OUT_DIR / f"{src.stem}.dark.svg"

            for expected, rendered in [(cur_light, out_light), (cur_dark, out_dark)]:
                if not expected.exists():
                    changed.append(f"missing: {expected.relative_to(ROOT)}")
                    continue
                if _sha256(expected) != _sha256(rendered):
                    changed.append(expected.relative_to(ROOT).as_posix())

        shutil.rmtree(tmp)

        if changed:
            print("D2 diagrams are out of date. Re-render with:")
            print("  python scripts/render_d2_diagrams.py\n")
            for p in changed:
                print(f" - {p}")
            raise SystemExit(1)

        print("D2 diagrams are up to date.")
        return

    for src in d2_files:
        out_light = OUT_DIR / f"{src.stem}.light.svg"
        out_dark = OUT_DIR / f"{src.stem}.dark.svg"

        _render_one(src, out_light, theme=cfg.theme_light, cfg=cfg)
        _render_one(src, out_dark, theme=cfg.theme_dark, cfg=cfg)

        # Compatibility: keep <name>.svg as the light variant.
        compat = OUT_DIR / f"{src.stem}.svg"
        shutil.copyfile(out_light, compat)

        print(f"Rendered: {out_light.relative_to(ROOT)}")
        print(f"Rendered: {out_dark.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1:])
