"""Render D2 diagrams used by the docs.

We keep D2 sources under:

  docs/assets/diagrams/src/*.d2

and render SVG outputs to:

  docs/assets/diagrams/*.light.svg
  docs/assets/diagrams/*.dark.svg

Why two files?
Material for MkDocs toggles themes via `data-md-color-scheme` ("default" vs "slate").
SVGs generated by D2 can optionally react to *OS* theme via media queries, but that
doesn't track the MkDocs palette toggle. Rendering two explicit variants avoids
surprises when switching the site theme.

Usage:
  python scripts/render_d2_diagrams.py
  python scripts/render_d2_diagrams.py --check

Environment overrides:
  D2_LAYOUT=elk
  D2_THEME_LIGHT=5
  D2_THEME_DARK=200
  D2_PAD=0

Install D2:
  - curl -fsSL https://d2lang.com/install.sh | sh -s --
  - go install oss.terrastruct.com/d2@latest
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "docs" / "assets" / "diagrams" / "src"
OUT_DIR = ROOT / "docs" / "assets" / "diagrams"
FRAGILE_SVG_TAGS = {"foreignObject", "image"}
FULL_CANVAS_RECT_RE = re.compile(
    r'(<svg class="d2-[^"]+ d2-svg"[^>]*>)'
    r'(<rect\b[^>]*\brx="0\.000000"[^>]*\bstroke-width="0"\s*/>)',
    re.S,
)


@dataclass(frozen=True, slots=True)
class D2RenderConfig:
    layout: str
    theme_light: str
    theme_dark: str
    pad: str
    center: bool = True
    no_xml_tag: bool = True


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _d2_binary() -> str:
    d2 = shutil.which("d2")
    if d2:
        return d2

    raise FileNotFoundError(
        "Could not find the `d2` executable on PATH.\n\n"
        "Install D2 and re-run:\n"
        "  1) curl -fsSL https://d2lang.com/install.sh | sh -s --\n"
        "  2) go install oss.terrastruct.com/d2@latest\n"
    )


def _local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def _format_svg_dimension(value: float) -> str:
    return str(int(value)) if value.is_integer() else f"{value:g}"


def _parse_viewbox_dimensions(value: str | None) -> tuple[str, str] | None:
    if not value:
        return None

    parts = value.replace(",", " ").split()
    if len(parts) != 4:
        return None

    try:
        width = float(parts[2])
        height = float(parts[3])
    except ValueError:
        return None

    if width <= 0 or height <= 0:
        return None

    return (_format_svg_dimension(width), _format_svg_dimension(height))


def _infer_root_dimensions(root: ET.Element) -> tuple[str, str] | None:
    nested_svg = next(
        (child for child in root if _local_name(child.tag) == "svg"), None
    )
    if nested_svg is not None:
        nested_width = nested_svg.get("width")
        nested_height = nested_svg.get("height")
        if nested_width and nested_height:
            return (nested_width, nested_height)

        nested_viewbox = _parse_viewbox_dimensions(nested_svg.get("viewBox"))
        if nested_viewbox is not None:
            return nested_viewbox

    return _parse_viewbox_dimensions(root.get("viewBox"))


def _normalize_rendered_svg_root(path: Path) -> None:
    svg_text = path.read_text(encoding="utf-8")
    svg_text = FULL_CANVAS_RECT_RE.sub(r"\1", svg_text, count=1)
    start_tag = re.match(r"<svg\b([^>]*)>", svg_text)
    if start_tag is None:
        raise RuntimeError(
            f"Rendered SVG is missing a root <svg> tag: {path.relative_to(ROOT)}"
        )

    try:
        root = ET.fromstring(svg_text)
    except ET.ParseError as exc:
        raise RuntimeError(
            f"Rendered SVG is not well-formed XML: {path.relative_to(ROOT)} ({exc})"
        ) from exc

    if _local_name(root.tag) != "svg":
        raise RuntimeError(
            f"Rendered asset is not an SVG document root: {path.relative_to(ROOT)}"
        )

    width = root.get("width")
    height = root.get("height")
    if not width or not height:
        inferred = _infer_root_dimensions(root)
        if inferred is None:
            raise RuntimeError(
                "Rendered SVG is missing root width/height and no fallback dimensions "
                f"could be inferred: {path.relative_to(ROOT)}"
            )
        width = width or inferred[0]
        height = height or inferred[1]

    attrs = start_tag.group(1)
    if not root.get("width"):
        attrs += f' width="{width}"'
    if not root.get("height"):
        attrs += f' height="{height}"'

    path.write_text(f"<svg{attrs}>{svg_text[start_tag.end():]}", encoding="utf-8")


def _validate_rendered_svg_contract(path: Path) -> None:
    try:
        tree = ET.parse(path)
    except ET.ParseError as exc:
        raise RuntimeError(
            f"Rendered SVG is not well-formed XML: {path.relative_to(ROOT)} ({exc})"
        ) from exc

    root = tree.getroot()
    if _local_name(root.tag) != "svg":
        raise RuntimeError(
            f"Rendered asset is not an SVG document: {path.relative_to(ROOT)}"
        )

    missing_root_attrs = [
        attr for attr in ("width", "height", "viewBox") if not root.get(attr)
    ]
    if missing_root_attrs:
        detail = ", ".join(missing_root_attrs)
        raise RuntimeError(
            "Rendered SVG is missing required root attributes in "
            f"{path.relative_to(ROOT)} ({detail})"
        )

    counts: dict[str, int] = {}
    for element in root.iter():
        name = _local_name(element.tag)
        if name in FRAGILE_SVG_TAGS:
            counts[name] = counts.get(name, 0) + 1

    if not counts:
        return

    detail = ", ".join(f"{tag}={count}" for tag, count in sorted(counts.items()))
    raise RuntimeError(
        "Rendered SVG uses fragile constructs in "
        f"{path.relative_to(ROOT)} ({detail}). "
        "Prefer plain text labels and shape fills in the D2 source so the docs "
        "render reliably on GitHub Pages and across browsers."
    )


def _render_one(src: Path, out: Path, *, theme: str, cfg: D2RenderConfig) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)

    cmd: list[str] = [
        _d2_binary(),
        f"--layout={cfg.layout}",
        f"--theme={theme}",
        f"--pad={cfg.pad}",
    ]

    if cfg.center:
        cmd.append("--center")
    if cfg.no_xml_tag:
        cmd.append("--no-xml-tag")

    cmd.extend([str(src), str(out)])
    subprocess.run(cmd, check=True)
    _normalize_rendered_svg_root(out)
    _validate_rendered_svg_contract(out)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write outputs. Fail if rendered SVGs would change.",
    )
    args = parser.parse_args(argv)

    if not SRC_DIR.exists():
        print(f"No D2 source directory found: {SRC_DIR}")
        return

    d2_files = sorted(SRC_DIR.glob("*.d2"))
    if not d2_files:
        print(f"No .d2 files found under {SRC_DIR}")
        return

    cfg = D2RenderConfig(
        layout=os.environ.get("D2_LAYOUT", "elk"),
        theme_light=os.environ.get("D2_THEME_LIGHT", "5"),
        theme_dark=os.environ.get("D2_THEME_DARK", "200"),
        pad=os.environ.get("D2_PAD", "0"),
        center=os.environ.get("D2_CENTER", "1") not in {"0", "false", "False"},
        no_xml_tag=os.environ.get("D2_NO_XML_TAG", "1") not in {"0", "false", "False"},
    )

    if args.check:
        tmp = ROOT / ".tmp_d2_render"
        if tmp.exists():
            shutil.rmtree(tmp)
        tmp.mkdir(parents=True, exist_ok=True)

        changed: list[str] = []
        for src in d2_files:
            out_light = tmp / f"{src.stem}.light.svg"
            out_dark = tmp / f"{src.stem}.dark.svg"

            _render_one(src, out_light, theme=cfg.theme_light, cfg=cfg)
            _render_one(src, out_dark, theme=cfg.theme_dark, cfg=cfg)

            cur_light = OUT_DIR / f"{src.stem}.light.svg"
            cur_dark = OUT_DIR / f"{src.stem}.dark.svg"

            for expected, rendered in [(cur_light, out_light), (cur_dark, out_dark)]:
                if not expected.exists():
                    changed.append(f"missing: {expected.relative_to(ROOT)}")
                    continue
                if _sha256(expected) != _sha256(rendered):
                    changed.append(expected.relative_to(ROOT).as_posix())

        shutil.rmtree(tmp)

        if changed:
            print("D2 diagrams are out of date. Re-render with:")
            print("  python scripts/render_d2_diagrams.py\n")
            for p in changed:
                print(f" - {p}")
            raise SystemExit(1)

        print("D2 diagrams are up to date.")
        return

    for src in d2_files:
        out_light = OUT_DIR / f"{src.stem}.light.svg"
        out_dark = OUT_DIR / f"{src.stem}.dark.svg"

        _render_one(src, out_light, theme=cfg.theme_light, cfg=cfg)
        _render_one(src, out_dark, theme=cfg.theme_dark, cfg=cfg)

        # Compatibility: keep <name>.svg as the light variant.
        compat = OUT_DIR / f"{src.stem}.svg"
        shutil.copyfile(out_light, compat)

        print(f"Rendered: {out_light.relative_to(ROOT)}")
        print(f"Rendered: {out_dark.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1:])
